name: Start Push-Workflow
run-name: ${{ github.actor }} is Pushing his branch
on: [push]
jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - run: ng buid
  start-unit-test:
    - run: ng test
  start-e2e-test:
    - run: npm run e2e