name: Start Push-Workflow
run-name: ${{ github.actor }} is pushing his branch
on: [push]
jobs:
  install_packages:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
    steps:
      - uses: actions/checkout@v4
      # - name: Setup Node.js 20
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 20.9.0
          # cache: 'npm'
          # cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build Angular project
        run: npm run build --configuration=$ENVIRONMENTS
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
      # - name: Unit-Test
      #   run: npm run test:prod
