name: Start Push-Workflow
run-name: ${{ github.actor }} is pushing his branch
on: [push]
jobs:
  install_packages:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build Angular project
        run: npm run build --configuration=$ENVIRONMENTS
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
      - name: Run Karma Config
        run: npm i --save-dev karma karma-chrome-launcher karma-mocha karma-chai
      - name: run mocha  
        run: npm i --save-dev mocha chai
      - name: Unit-Test
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI