name: Start Push-Workflow
run-name: ${{ github.actor }} is Pushing his branch
on: [push]
jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      # - run: npx bookmonkey-api
  run-build:
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
  # start-unit-test:
  #   - run: npm run test
  # start-e2e-test:
  #   - run: npm run e2e