name: Start Push-Workflow
run-name: ${{ github.actor }} is Pushing his branch
on: [push]
jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - run: ng buid
jobs: 
  start-unit-test:
  runs-on: ubuntu-latest
  steps:
    - run: ng test
jobs: 
  start-e2e-test:
  runs-on: ubuntu-latest
  steps:
    - run:  npm run e2e