name: Start Push-Workflow
run-name: ${{ github.actor }} is Pushing his branch
on: [push]
jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      # - run: npm install
      # - run: npx bookmonkey-api
  # run-build:
  #   runs-on: ubuntu-latest
    # steps:
      - name: Install dependencies
        run: npm ci
  # start-unit-test:
  #   - run: npm run test
  # start-e2e-test:
  #   - run: npm run e2e